export type { AppState, AppView, AppSettings, FontSize, SortOrder, ItemData, SearchResultItem, SearchDefinition } from './types';
export type { ExpansionCounts } from './store';
export { createItemData } from './types';

export {
  // Actions
  upsertItem,
  upsertItems,
  setItemContent,
  toggleItemSelected,
  toggleItemExpanded,
  setItemSelected,
  setItemExpanded,
  setItemEditing,
  setItemRenaming,
  setHighlightItem,
  clearAllSelections,
  selectItemsByPaths,
  expandAllItems,
  collapseAllItems,
  clearAllCutItems,
  cutSelectedItems,
  deleteItems,
  getItem,
  isCacheValid,
  setCurrentView,
  setCurrentPath,
  navigateToBrowserPath,
  clearPendingScrollToFile,
  setPendingScrollToFile,
  setSearchResults,
  clearSearchResults,
  setSettings,
  setFontSize,
  setSortOrder,
  setFoldersOnTop,
  setIgnoredPaths,
  getSettings,
  getExpansionCounts,
  // Hooks
  useAppState,
  useItems,
  useItem,
  useCurrentView,
  useCurrentPath,
  usePendingScrollToFile,
  useSearchResults,
  useSearchQuery,
  useSearchFolder,
  useSettings,
  useHighlightItem,
  useExpansionCounts,
} from './store';
