export type { AppState, AppView, AppSettings, FontSize, SortOrder, ContentWidth, ItemData, SearchResultItem, SearchDefinition, ScrollPositions } from './types';
export type { ExpansionCounts } from './store';
export { createItemData } from './types';

export {
  // Actions
  upsertItem,
  upsertItems,
  setItemContent,
  toggleItemSelected,
  toggleItemExpanded,
  setItemSelected,
  setItemExpanded,
  setItemEditing,
  clearItemGoToLine,
  setItemRenaming,
  setHighlightItem,
  clearAllSelections,
  selectItemsByPaths,
  expandAllItems,
  collapseAllItems,
  clearAllCutItems,
  cutSelectedItems,
  deleteItems,
  clearCache,
  getItem,
  isCacheValid,
  setCurrentView,
  setCurrentPath,
  setBrowserScrollPosition,
  getBrowserScrollPosition,
  setSearchResultsScrollPosition,
  getSearchResultsScrollPosition,
  setSettingsScrollPosition,
  getSettingsScrollPosition,
  navigateToBrowserPath,
  clearPendingScrollToFile,
  setPendingScrollToFile,
  setPendingEditFile,
  clearPendingEditFile,
  setSearchResults,
  clearSearchResults,
  setSettings,
  setFontSize,
  setSortOrder,
  setFoldersOnTop,
  setIgnoredPaths,
  setContentWidth,
  toggleBookmark,
  isBookmarked,
  updateBookmarkPath,
  getSettings,
  getExpansionCounts,
  // Hooks
  useAppState,
  useItems,
  useItem,
  useCurrentView,
  useCurrentPath,
  usePendingScrollToFile,
  usePendingEditFile,
  usePendingEditLineNumber,
  useSearchResults,
  useSearchQuery,
  useSearchFolder,
  useSettings,
  useHighlightItem,
  useExpansionCounts,
  useScrollPositions,
} from './store';
