files:
  - name: federalist-01-00.md
    id: F0D0D1EC8
  - name: federalist-01-01.md
    id: 2EABB973F
  - name: federalist-01-02.md
    id: 687DBE236
  - name: federalist-01-03.md
    id: 53455D762
  - name: federalist-01-04.md
    id: 9245C0688
  - name: federalist-01-05.md
    id: 66C1AB7D2
  - name: federalist-01-06.md
    id: B3C62EAA3
  - name: federalist-01-07.md
    id: 02A05F7B4
  - name: federalist-01-08.md
    id: E48183A6C
  - name: federalist-01-09.md
    id: 44D1AD64B
  - name: federalist-01-10.md
    id: 6513BCB17
options:
  edit_mode: false
