import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import type { ThesaurusLookup } from '../shared/shared';

/**
 * Thesaurus lookups for the editor's synonym pane.
 *
 * Backed by `resources/thesaurus/moby.txt.gz`, generated by the repo-root
 * `build-thesaurus.mjs` (see its header for the sources, the file format, and why Moby
 * rather than WordNet). The file holds two kinds of line in one namespace:
 *
 *     huge\tAtlantean,Brobdingnagian,Cyclopean,Gargantuan,abysmal,astronomic,...
 *     took\t=take
 *
 * A synonym line carries the list; an alias line points an inflected form at the root that
 * holds them. The generator guarantees no synonym contains a tab and that nothing in Moby
 * begins with `=`, so both splits are unambiguous. Words are lowercased on both sides.
 *
 * MAIN PROCESS ONLY — uses `node:fs`.
 */

// The parsed index, built at most once per session. ~30k entries holding 2.5M synonyms,
// resident only after a first lookup: the file is never touched unless the user opens the
// editor.
let entries: Map<string, string> | null = null;
let loadingPromise: Promise<Map<string, string>> | null = null;

/** Marks an alias line's value (see the file-format note above). */
const ALIAS_PREFIX = '=';

/**
 * Suffix rules for reducing a regularly inflected word to the form Moby indexes.
 *
 * Moby is keyed by root words only — it has "walk" but not "walked", "create" but not
 * "creating" — while prose is mostly inflected, so without reduction the pane would find
 * nothing for a large share of the words a cursor lands on.
 *
 * These rules are the *fallback*, consulted only after the alias table (which covers every
 * inflection AGID knows, irregulars included) has missed. They still earn their place:
 * measured against AGID over ~284k words of prose they fired on 5,072 words and produced a
 * root AGID does not recognise only 6 times, and they keep working for words AGID has no
 * record of at all.
 *
 * Longer suffixes come first so the specific forms get their chance before a shorter rule
 * reduces them to something wrong.
 */
const DETACHMENT_RULES: readonly (readonly [string, string])[] = [
  ['iest', 'y'], ['ies', 'y'], ['ied', 'y'], ['ier', 'y'],
  ['ches', 'ch'], ['shes', 'sh'], ['ses', 's'], ['xes', 'x'], ['zes', 'z'],
  ['men', 'man'],
  ['ing', 'e'], ['ing', ''],
  ['est', 'e'], ['est', ''],
  ['ed', 'e'], ['ed', ''],
  ['er', 'e'], ['er', ''],
  ['es', 'e'], ['es', ''],
  ['s', ''],
];

/**
 * Shortest root a detachment rule may produce. Without this, stripping "-ed" from "bed"
 * offers "be", and a one- or two-letter stem is far more often an accident of spelling
 * than a real root. Matches the minimum word length the editor plugin reports.
 */
const MIN_ROOT_LENGTH = 3;

/**
 * Resolves the shipped data file. Mirrors the dictionary's dev-vs-packaged branch in
 * `main.ts` — `extraResource` puts `resources/thesaurus` directly under `resourcesPath`.
 */
function thesaurusFilePath(resourcesPath: string, appPath: string, isPackaged: boolean): string {
  return isPackaged
    ? path.join(resourcesPath, 'thesaurus', 'moby.txt.gz')
    : path.join(appPath, 'resources', 'thesaurus', 'moby.txt.gz');
}

/**
 * Parses the decompressed data file into its lookup map, holding both kinds of line (see
 * the file-format note above) in one namespace. Each value is stored as the raw string and
 * interpreted only when that key is looked up — eagerly splitting 2.5 million synonyms
 * would cost far more memory than the raw text, to produce arrays almost none of which are
 * ever read.
 */
export function parseThesaurus(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of text.split('\n')) {
    const tab = line.indexOf('\t');
    if (tab === -1) continue;
    map.set(line.slice(0, tab), line.slice(tab + 1));
  }
  return map;
}

/**
 * Resolves one candidate key to the word that actually holds synonyms, or null.
 *
 * A key is either a synonym entry (resolves to itself) or an alias pointing at one. The hop
 * is deliberately single, never chained: the generator guarantees every alias target is a
 * real synonym entry, and checking the target exists means a malformed file degrades to
 * "no synonyms" rather than to a wrong answer or a loop.
 */
function resolveKey(key: string, index: Map<string, string>): string | null {
  const value = index.get(key);
  if (value === undefined) return null;
  if (!value.startsWith(ALIAS_PREFIX)) return key;

  const root = value.slice(ALIAS_PREFIX.length);
  return index.has(root) ? root : null;
}

/**
 * Reduces `word` to a key present in `entries` that holds synonyms, or returns null.
 *
 * Order is exact match (including an alias for the word as written), then the suffix rules.
 * Trying the word as written first is what keeps real words safe — "bed" and "seed" are
 * entries in their own right and never reach the rule that would strip them to "be" and
 * "see". A rule's output is only accepted if it resolves to a real key, so a rule firing on
 * the wrong kind of word almost always produces a non-word and is discarded.
 *
 * The alias table takes precedence over the rules on purpose: it is authoritative
 * morphology, the rules are a heuristic. That ordering is what makes "does" resolve to "do"
 * rather than to "doe", which the `-es`/`-e` rule would otherwise reach first.
 */
export function findRoot(word: string, index: Map<string, string>): string | null {
  const direct = resolveKey(word, index);
  if (direct !== null) return direct;

  for (const [suffix, replacement] of DETACHMENT_RULES) {
    if (!word.endsWith(suffix)) continue;
    const candidate = word.slice(0, word.length - suffix.length) + replacement;
    if (candidate.length < MIN_ROOT_LENGTH) continue;
    const resolved = resolveKey(candidate, index);
    if (resolved !== null) return resolved;
  }

  return null;
}

/**
 * Reorders an entry so the plain single words come before the compound terms — anything
 * carrying a space or a hyphen ("walk of life", "first-rate").
 *
 * Moby's entries mix the two freely and are alphabetical, so a big entry ("cut" has 1446)
 * scatters "take the air" and "good-looking" among the plain words. Since the pills wrap in
 * reading order, that leaves the short, most-reachable-for-a-word-swap options strewn across
 * eight rows. Grouping them puts every one-word choice up front, where the user is looking.
 *
 * A single pass into two buckets rather than a sort: it is O(n) instead of O(n log n), it
 * tests each string once instead of once per comparison, and — the part that actually
 * matters — it preserves Moby's alphabetical order *within* each group for free, where a
 * comparator would be relying on the sort being stable to do the same.
 */
export function singleWordsFirst(synonyms: string[]): string[] {
  const words: string[] = [];
  const compounds: string[] = [];
  for (const synonym of synonyms) {
    // Two `includes` rather than a precompiled /[ -]/, which is the counter-intuitive one:
    // measured over all 2.5M shipped synonyms (avg 8.7 chars) two scans came in ~35% faster
    // than the regex — at this length the engine's per-character loop costs more than
    // running the SIMD single-character search twice, and there is no regex object at all.
    (synonym.includes(' ') || synonym.includes('-') ? compounds : words).push(synonym);
  }
  return words.concat(compounds);
}

/**
 * Loads and caches the index. Concurrent callers share the one in-flight promise, so the
 * ~25 MB decompress-and-parse happens exactly once even if several lookups race.
 */
function loadThesaurus(filePath: string): Promise<Map<string, string>> {
  if (entries) return Promise.resolve(entries);
  if (loadingPromise) return loadingPromise;

  loadingPromise = fs.promises
    .readFile(filePath)
    .then((gzipped) => {
      const parsed = parseThesaurus(zlib.gunzipSync(gzipped).toString('utf-8'));
      entries = parsed;
      return parsed;
    })
    .catch((err: unknown) => {
      // Clear the in-flight promise so a later lookup can retry rather than being stuck
      // with a rejected one forever; rethrow so this call still surfaces the failure.
      loadingPromise = null;
      throw err;
    });

  return loadingPromise;
}

/**
 * Looks up `word`, reducing it to its root form when the word as written has no entry.
 *
 * Returns the entry the synonyms actually belong to alongside them, so the pane can be
 * honest about it — a cursor on "walked" gets "walk"'s synonyms, and the user should be
 * able to see that is what happened. `lemma` is null when nothing was found.
 *
 * Lookup is case-insensitive; surrounding whitespace is ignored. The synonyms come back
 * single words first, phrases after (see `singleWordsFirst`) — ordering the list here rather
 * than in the pane keeps it a property of the data every caller gets, and costs one pass
 * over an array that was just built anyway.
 */
export async function lookupThesaurus(
  word: string,
  paths: { resourcesPath: string; appPath: string; isPackaged: boolean },
): Promise<ThesaurusLookup> {
  const key = word.trim().toLowerCase();
  if (key.length === 0) return { lemma: null, synonyms: [] };

  const index = await loadThesaurus(thesaurusFilePath(paths.resourcesPath, paths.appPath, paths.isPackaged));

  const root = findRoot(key, index);
  if (root === null) return { lemma: null, synonyms: [] };

  const synonyms = index.get(root);
  return { lemma: root, synonyms: synonyms === undefined ? [] : singleWordsFirst(synonyms.split(',')) };
}
