import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkStringify from 'remark-stringify';
import { toc } from 'mdast-util-toc';
import type { Root, Heading } from 'mdast';
import GithubSlugger from 'github-slugger';
import type { MarkdownHeadingNode } from '../store/types';

const START_TAG = '<!-- TOC -->';
const END_TAG = '<!-- /TOC -->';

/**
 * Generates or updates a Table of Contents in a Markdown string.
 *
 * The TOC is inserted between <!-- TOC --> and <!-- /TOC --> comment tags.
 * If only the opening tag is present, the closing tag is added automatically.
 * Returns the content unchanged if no START_TAG is found, if multiple
 * START_TAGs exist, or if the document contains no headings.
 *
 * Heading slugs are generated by mdast-util-toc using GitHub-style slugging,
 * which matches the rehype-slug plugin used in the renderer.
 */
/**
 * Strips the generated TOC body from content, leaving only the opening tag.
 * Used when loading content into the editor so the user sees <!-- TOC --> instead
 * of the full generated list.
 */
export function removeTOC(content: string): string {
  return content.replace(/<!--\s*TOC\s*-->[\s\S]*?<!--\s*\/TOC\s*-->/g, '<!-- TOC -->');
}

/**
 * Returns a sanitized copy of content safe for TOC generation by removing:
 * - Front matter: YAML block delimited by "---" on the very first line
 * - Fenced code blocks: backtick or tilde fences of any length (e.g. ```, ~~~~)
 * Headings inside these regions are ignored so they don't appear in the TOC.
 */
function sanitizeForTOC(content: string): string {
  const lines = content.split('\n');
  const out: string[] = [];
  let i = 0;

  // Strip front matter if the file starts with "---"
  if (lines[0]?.trim() === '---') {
    i = 1;
    while (i < lines.length && lines[i]?.trim() !== '---') i++;
    i++; // skip closing "---"
  }

  const firstI = i;
  // Process remaining lines, blanking fenced code blocks
  for (; i < lines.length; i++) {
    const line = lines[i];
    
    // table of contents always looks best when the first heading is skipped 
    // because it would be a repeat of what is already right at the top of the page 
    // and will normally be the title for the entire document also, which makes no 
    // sense to put in the table of contents 
    if (i==firstI && line && line.trim().startsWith("#")) continue;

    const fenceMatch = line.match(/^(`{3,}|~{3,})/);
    if (fenceMatch) {
      const fence = fenceMatch[1];
      const char = fence[0];
      const len = fence.length;
      out.push('');
      i++;
      while (i < lines.length) {
        const inner = lines[i];
        const closing = inner.match(/^(`+|~+)/);
        if (closing && closing[1][0] === char && closing[1].length >= len) {
          out.push('');
          break;
        }
        out.push('');
        i++;
      }
    } else {
      out.push(line);
    }
  }

  return out.join('\n');
}

export async function processTOC(content: string): Promise<string> {
  const sanitized = sanitizeForTOC(content);

  if (!sanitized.includes(START_TAG)) {
    return content;
  }

  const firstStart = sanitized.indexOf(START_TAG);
  if (sanitized.indexOf(START_TAG, firstStart + 1) !== -1) {
    return content;
  }

  const ast = unified().use(remarkParse).parse(sanitized) as Root;
  const result = toc(ast, { maxDepth: 3, tight: true });

  if (!result.map) {
    return content;
  }

  const tocMarkdown = (
    unified()
      .use(remarkStringify)
      .stringify({ type: 'root', children: [result.map] } as Root)
  ).trimEnd();

  const contentStart = content.indexOf(START_TAG);
  const afterStart = contentStart + START_TAG.length;
  const endIdx = content.indexOf(END_TAG, afterStart);

  if (endIdx !== -1) {
    return (
      content.slice(0, afterStart) +
      '\n\n' + tocMarkdown + '\n\n' +
      content.slice(endIdx)
    );
  }

  return (
    content.slice(0, afterStart) +
    '\n\n' + tocMarkdown + '\n\n' +
    END_TAG +
    content.slice(afterStart)
  );
}

function headingText(node: Heading): string {
  return node.children
    .map(child => ('value' in child ? child.value : ''))
    .join('');
}

/**
 * Parse a markdown string and return a tree of MarkdownHeadingNode objects.
 * Heading nesting follows depth (H1 > H2 > H3 …).
 * The synthetic `path` for each node is `filePath + '#' + flatIndex`.
 */
export function extractHeadingTree(filePath: string, content: string): MarkdownHeadingNode[] {
  const ast = unified().use(remarkParse).parse(content) as Root;
  const headings = ast.children.filter((n): n is Heading => n.type === 'heading');

  const slugger = new GithubSlugger();

  // Build nodes in order, assign synthetic paths and rehype-slug-compatible slugs
  const nodes: MarkdownHeadingNode[] = headings.map((h, i) => {
    const text = headingText(h);
    return {
      path: `${filePath}#${i}`,
      heading: text,
      slug: slugger.slug(text),
      depth: h.depth,
      isExpanded: false,
      isLoading: false,
      children: null,
    };
  });

  // Stack-based tree assembly: stack holds ancestors by depth
  const roots: MarkdownHeadingNode[] = [];
  const stack: MarkdownHeadingNode[] = [];

  for (const node of nodes) {
    // Pop stack until top has a lower depth than current node
    while (stack.length > 0 && stack[stack.length - 1].depth >= node.depth) {
      stack.pop();
    }

    if (stack.length === 0) {
      roots.push(node);
    } else {
      const parent = stack[stack.length - 1];
      if (!parent.children) parent.children = [];
      parent.children.push(node);
    }

    stack.push(node);
  }

  return roots;
}
