import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkStringify from 'remark-stringify';
import { toc } from 'mdast-util-toc';
import type { Root } from 'mdast';

const START_TAG = '<!-- TOC -->';
const END_TAG = '<!-- /TOC -->';

/**
 * Generates or updates a Table of Contents in a Markdown string.
 *
 * The TOC is inserted between <!-- TOC --> and <!-- /TOC --> comment tags.
 * If only the opening tag is present, the closing tag is added automatically.
 * Returns the content unchanged if no START_TAG is found, if multiple
 * START_TAGs exist, or if the document contains no headings.
 *
 * Heading slugs are generated by mdast-util-toc using GitHub-style slugging,
 * which matches the rehype-slug plugin used in the renderer.
 */
export async function processTOC(content: string): Promise<string> {
  if (!content.includes(START_TAG)) {
    return content;
  }

  const firstStart = content.indexOf(START_TAG);
  if (content.indexOf(START_TAG, firstStart + 1) !== -1) {
    return content;
  }

  const ast = unified().use(remarkParse).parse(content) as Root;
  const result = toc(ast, { maxDepth: 3, tight: true });

  if (!result.map) {
    return content;
  }

  const tocMarkdown = (
    unified()
      .use(remarkStringify)
      .stringify({ type: 'root', children: [result.map] } as Root)
  ).trimEnd();

  const afterStart = firstStart + START_TAG.length;
  const endIdx = content.indexOf(END_TAG, afterStart);

  if (endIdx !== -1) {
    return (
      content.slice(0, afterStart) +
      '\n\n' + tocMarkdown + '\n\n' +
      content.slice(endIdx)
    );
  }

  return (
    content.slice(0, afterStart) +
    '\n\n' + tocMarkdown + '\n\n' +
    END_TAG +
    content.slice(afterStart)
  );
}
