files:
  - name: federalist-04-00.md
    id: B894533E2
  - name: federalist-04-01.md
    id: 7A846CF61
  - name: federalist-04-02.md
    id: 33BCCE3E7
  - name: federalist-04-03.md
    id: AA1C2BBEE
  - name: federalist-04-04.md
    id: 23A3F5194
  - name: federalist-04-05.md
    id: C403436B0
  - name: federalist-04-06.md
    id: EF5DBE542
  - name: federalist-04-07.md
    id: 664577CF9
  - name: federalist-04-08.md
    id: F33077058
  - name: federalist-04-09.md
    id: 215089C5F
  - name: federalist-04-10.md
    id: A50637527
  - name: federalist-04-11.md
    id: 08C618CD0
  - name: federalist-04-12.md
    id: 5DD98DA2D
  - name: federalist-04-13.md
    id: 90FBFDE00
  - name: federalist-04-14.md
    id: 4168E1A4A
  - name: federalist-04-15.md
    id: 8DDA16258
  - name: federalist-04-16.md
    id: FC6C4698B
  - name: federalist-04-17.md
    id: E3CB4AEFD
options:
  edit_mode: true
